### ISSUE TITLE
Add a warning about unsupported `complete` event.

### ISSUE THREAD

**Issue by nfriedly** [bevry/taskgroup#24]
I've been bitten more than once by copying (presumably) working code that uses taskgroup (most recently https://github.com/docpad/docpad-plugin-multiplelayouts/blob/master/src/multiplelayouts.plugin.coffee#L31) and then pulling my hair out trying to figure out why it never completes.

Something like `console.warn(new Error("TaskGroup 'complete' event is deprecated, please use 'completed' instead"))` would save the day (or at least what's left of my hair ;)

**Comment by balupton** [comment]
Hrmmm, I will see what I can do. There is a ES6 rewrite of TaskGroup in the works, which redoes a lot of the API.

For deprecation, v4 made it so you should use `.done` instead of a `complete` or `completed` event directly, as noted in https://github.com/bevry/taskgroup/blob/master/HISTORY.md#v400-june-16-2014 - however, I guess if one was not aware of this change, and saw v3 taskgroup client code, then they are in for a nightmare.

Thanks for bringing this to my attention, definitely something I overlooked. I will see what I can do, and will leave this open until a solution is applied.

**Comment by balupton** [comment]
Considering this change was in 2014, I'll close this as no longer relevant.

However for upcoming releases, I'll see what I can do about deprecation warnings for changed things.
